import { Poppins} from 'next/font/google'
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";


const poppins = Poppins({
  weight: ['400', '500', '600', '800', '900'],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
      >
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
