import { Poppins} from 'next/font/google'
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import ReduxProvider from '@/providers/ReduxProvider';
import Footer from '@/components/footer/Footer';


const poppins = Poppins({
  weight: ['400', '500', '600', '800', '900'],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <ReduxProvider>
       <body
        className={poppins.className}
      >
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </body>
     </ReduxProvider>
    </html>
  );
}
