import { Poppins} from 'next/font/google'
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import ReduxProvider from '@/providers/ReduxProvider';
import Footer from '@/components/footer/Footer';
import { ToastContainer } from 'react-toastify';
import NextAuthSessionProvider from '@/providers/NextAuthSessionProvider';


const poppins = Poppins({
  weight: ['400', '500', '600', '800', '900'],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <NextAuthSessionProvider>
       <ReduxProvider>
       <body
        className={poppins.className}
      >
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        <ToastContainer
        position="top-center"
         />
      </body>
     </ReduxProvider>
    </NextAuthSessionProvider>
    </html>
  );
}
